package at

// wargames help
var help = []string{`HELP NOT AVAILABLE`}
var helpGames = []string{
	`'GAMES' REFERS TO MODELS, SIMULATIONS, AND GAMES WICH HAVE ` +
		`TACTICAL AND STRATEGIC APPLICATIONS.`,
}
var listGames = []string{
	`FALKEN'S MAZE`,
	`BLACK JACK`,
	`GIN RUMMY`,
	`HEARTS`,
	`BRIDGE`,
	`CHECKERS`,
	`CHESS`,
	`POKER`,
	`FIGHTER COMBAT`,
	`GUERRILLA ENGAGEMENT`,
	`DESERT WARFARE`,
	`AIR-TO-GROUND ACTIONS`,
	`THEATERWIDE TACTICAL WARFARE`,
	`THEATERWIDE BIOTOXIC AND CHEMICAL WARFARE`,
	``,
	`GLOBAL THERMONUCLEAR WAR`,
}
